#!/bin/bash
cd ../..

for dependency in cmake; do
	command -v $dependency >/dev/null 2>&1 || { echo >&2 "Please install package $dependency."; exit 1; }
done

if [ ! -d android/assets/glsl/opt ]; then
	mkdir android/assets/glsl/opt
fi

if [ ! -d .temp/glsl-optimizer ]; then
	mkdir -p .temp/glsl-optimizer
fi

if [ ! -f .temp/glsl-optimizer/glsl_compiler ]; then

	cd .temp/glsl-optimizer

	if [ ! -f contrib/glslopt/Makefile ]; then
		git clone https://github.com/aras-p/glsl-optimizer.git .
	fi

	cmake .
	make

	cd ../..
fi

for shaderPath in android/assets/glsl/*; do
	if [ -f $shaderPath ]; then
		shaderDirectory=$(dirname "$shaderPath")
		filename=$(basename "$shaderPath")
		extension="${filename##*.}"
		filename="${filename%.*}"
		firstLetter=${extension:0:1}
		outfile=$shaderDirectory/opt/$filename.$extension
		.temp/glsl-optimizer/glslopt -$firstLetter $shaderPath $outfile
		echo $shaderPath
	fi
done

echo Done!
